server:
  port: 8080

---

spring:
  profiles: default
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:mysql://street12db.cf4uv8oilikl.ap-northeast-2.rds.amazonaws.com:3306/street12db
    username: admin
    password: 12street
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
        ddl-auto: create
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: payment
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json

#logging:
#  path: /logs/order
#  file:
#    max-history: 30
#  level:
#    org.springframework.cloud: debug


server:
  port: 8085
---

spring:
  profiles: docker
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:mysql://street12db.cf4uv8oilikl.ap-northeast-2.rds.amazonaws.com:3306/street12db
    username: admin
    password: 12street
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: payment
          destination: eventTopic
          contentType: application/json
        event-out:
          destination: eventTopic
          contentType: application/json

#logging:
#  path: /logs/order
#  file:
#    max-history: 30
#  level:
#    org.springframework.cloud: debug